// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using V2GELENZAMLARV2.Data;

#nullable disable

namespace V2GELENZAMLARV2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("V2GELENZAMLARV2.Products", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UrunID"));

                    b.Property<string>("Urun2015Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urun2016Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urun2017Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urun2018Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urun2019Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urun2020Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urun2021Fiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrunAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrunBilgisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrunGuncelFiyat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UrunID");

                    b.ToTable("Urunlerim");
                });
#pragma warning restore 612, 618
        }
    }
}
